name: Sync to cloud server

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  sync_to_srv_data:
    runs-on: [self-hosted, linux, x64]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - name: Sync repo to /srv/data/gitops
        run: |
          mkdir -p /srv/data/gitops
          rsync -a --delete \
            --exclude '.git/' \
            --exclude '.github/' \
            "${GITHUB_WORKSPACE}/" \
            /srv/data/gitops/

      - name: Docker compose up
        working-directory: /srv/data/gitops/docker
        run: |
          docker compose --env-file /opt/docker-secrets/data.env up -d --remove-orphans
